server:
  port: 8080
eureka:
  client:
    region: default
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: "http://localhost:8010/eureka/"
jwt:
  secret: "SECRET"
  token:
    accessToken:
      validity: "300000"
    refreshToken:
      validity: "86400000"
spring:
  application:
    name: gateway
  #cloud:
  #  gateway:
  #    routes:
  #    - id: SELLER-ADD-PRODUCT
  #      uri: http://localhost:8020/
  #      predicates:
  #      - Path=/e-auction/api/v1/seller/add-product/**
  #    - id: SELLER-DELETE-PRODUCT
  #      uri: http://localhost:8020/
  #      predicates:
  #      - Path=/e-auction/api/v1/seller/delete/**  
  #    - id: BUYER
  #      uri: http://localhost:8040/
  #      predicates:
  #     - Path=/e-auction/api/v1/buyer/**
  #    - id: LISTING
  #      uri: http://localhost:8060/
  #      predicates:
  #      - Path=/e-auction/api/v1/seller/show-bids/**  
                